title: My awesome EUROs title
author: Ryan Brinklow
email: myemail@secret.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here, Okay. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: ryanbrinklow98 # DO NOT include the @ character, or else the build will fail!
github_username:  RyanBrinklow # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
